### ISSUE TITLE
Couldn't Create new Project w Cybele

### ISSUE THREAD

**Issue by puskuruk** [lab2023/cybele#128]
I use debian 9 on my x230.
I use rbenv for ruby version control.
U use ruby 2.5.1 globally.
When I made 
```shell
cybele new
```
I take this errors:
```shell
Fetching rugged 0.27.2
Installing rugged 0.27.2 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/puskuruk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rugged-0.27.2/ext/rugged
/home/puskuruk/.rbenv/versions/2.5.1/bin/ruby -r ./siteconf20180802-25630-92tc2p.rb extconf.rb
checking for gmake... no
checking for make... yes
checking for cmake... no
ERROR: CMake is required to build Rugged.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/home/puskuruk/.rbenv/versions/2.5.1/bin/$(RUBY_BASE_NAME)
	--with-sha1dc
	--without-sha1dc
	--use-system-libraries

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/puskuruk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/extensions/x86_64-linux/2.5.0-static/rugged-0.27.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/puskuruk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rugged-0.27.2 for inspection.
Results logged to
/home/puskuruk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/extensions/x86_64-linux/2.5.0-static/rugged-0.27.2/gem_make.out

An error occurred while installing rugged (0.27.2), and Bundler cannot continue.
Make sure that `gem install rugged -v '0.27.2' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  pronto-poper was resolved to 0.9.1, which depends on
    poper was resolved to 0.2.1, which depends on
      rugged
      append  Gemfile
      append  Gemfile
      append  Gemfile
      append  Gemfile
      append  Gemfile
      append  Gemfile
         run  bundle install --binstubs=bin/stubs
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/.
You have requested:
  thor ~> 0.19.4

The bundle currently has thor locked at 0.20.0.
Try running `bundle update thor`

If you are updating multiple gems in your Gemfile at once,
try passing them all to `bundle update`
Add .editor_config file
      create  .editorconfig
Add .VERSION.txt file
      create  VERSION.txt
         run  ln -s ../VERSION.txt public/VERSION.txt from "."
Remove files we don't need
      remove  README.rdoc
Generate config
    generate  config:install
Traceback (most recent call last):
	25: from /home/puskuruk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.0.2/bin/spring:49:in `<main>'
	24: from /home/puskuruk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
	23: from /home/puskuruk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
	22: from /home/puskuruk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/client/server.rb:9:in `call'
	21: from /home/puskuruk/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	20: from /home/puskuruk/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	19: from /home/puskuruk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/server.rb:9:in `<top (required)>'
	18: from /home/puskuruk/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	17: from /home/puskuruk/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	16: from /home/puskuruk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/commands.rb:4:in `<top (required)>'
	15: from /home/puskuruk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/commands.rb:33:in `<module:Spring>'
	14: from /home/puskuruk/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	13: from /home/puskuruk/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	12: from /home/puskuruk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/setup.rb:20:in `<top (required)>'
	11: from /home/puskuruk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler.rb:107:in `setup'
	10: from /home/puskuruk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/runtime.rb:20:in `setup'
	 9: from /home/puskuruk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/runtime.rb:108:in `block in definition_method'
	 8: from /home/puskuruk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/definition.rb:227:in `requested_specs'
	 7: from /home/puskuruk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/definition.rb:238:in `specs_for'
	 6: from /home/puskuruk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/definition.rb:171:in `specs'
	 5: from /home/puskuruk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/definition.rb:258:in `resolve'
	 4: from /home/puskuruk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/resolver.rb:22:in `resolve'
	 3: from /home/puskuruk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/resolver.rb:48:in `start'
	 2: from /home/puskuruk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/resolver.rb:257:in `verify_gemfile_dependencies_are_found!'
	 1: from /home/puskuruk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/resolver.rb:257:in `each'
/home/puskuruk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/resolver.rb:289:in `block in verify_gemfile_dependencies_are_found!': You have requested: (Bundler::GemNotFound)
  thor ~> 0.19.4

The bundle currently has thor locked at 0.20.0.
Try running `bundle update thor`

If you are updating multiple gems in your Gemfile at once,
try passing them all to `bundle update`
         run  cp config/settings/development.yml config/settings/staging.yml from "."
cp: 'config/settings/development.yml' durumlanamadı: Böyle bir dosya ya da dizin yok
      append  config/settings.yml
The file /home/puskuruk/is/davetiyeli/new/config/settings.yml does not appear to exist
```

When I made: 
```shell
bundle update thor
```

I take this error:
```shell
Installing rugged 0.27.2 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/puskuruk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rugged-0.27.2/ext/rugged
/home/puskuruk/.rbenv/versions/2.5.1/bin/ruby -r ./siteconf20180802-26096-arwcb5.rb extconf.rb
checking for gmake... no
checking for make... yes
checking for cmake... no
ERROR: CMake is required to build Rugged.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/home/puskuruk/.rbenv/versions/2.5.1/bin/$(RUBY_BASE_NAME)
	--with-sha1dc
	--without-sha1dc
	--use-system-libraries

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/puskuruk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/extensions/x86_64-linux/2.5.0-static/rugged-0.27.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/puskuruk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rugged-0.27.2 for inspection.
Results logged to
/home/puskuruk/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/extensions/x86_64-linux/2.5.0-static/rugged-0.27.2/gem_make.out

An error occurred while installing rugged (0.27.2), and Bundler cannot continue.
Make sure that `gem install rugged -v '0.27.2' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  pronto-poper was resolved to 0.9.1, which depends on
    poper was resolved to 0.2.1, which depends on
      rugged

```

I tried those too..
```shell
rbenv uninstall 2.5.1 && rbenv install 2.5.1 && rbenv global 2.5.1 && rbenv rehash
```
Can you help me?

Have a nice day!

**Comment by muratrahmikurtul** [comment]
Hi puskuruk,

Try

`sudo apt-get install cmake`

then bundle again.

Have a nice day!

**Comment by ismailakbudak** [comment]
Hi @puskuruk,

We will close this issue if it is solved?

**Comment by puskuruk** [comment]
I changed my system to "Pop_OS 18.10". I don't know is there a still problem with "Debian 9". But when I install `cybele` on my current system and execute `cybele example` it works without any problem . 

You can close this issue.

And when I read error message again you can be right @muratrahmikurtul. But I had cmake. I really don't know what was the problem. 

Thank you @muratrahmikurtul && @ismailakbudak . 

Have a nice day!
